---
- name: Zabbix test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6002
  rules:
    - name: debug
      condition: event.payload is defined
      action:
        debug:
