---
- name: Zabbix Conditional Automation
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: run
      condition: event.payload.event_name is match("Network Options", ignorecase=true)
      action:
        run_job_template: 
          name: Network Options Set 
          organization: Default
          job_args:
            key: "tcp_recvspace"
