---
- name: Zabbix Conditional Automation
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6001
  rules:
    - name: run
      condition: event.payload is defined
      action:
        run_job_template: 
          name: Network Options 
          organization: Default
          job_args:
            key: "tcp_recvspace"
