---
- name: Zabbix Conditional Automation
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6001
  rules:
    - name: run
      condition: event.payload.event_tags.playbook is select("==", "Network Options")
      action:
        run_job_template: 
          name: Network Options 
          organization: Default
          job_args:
            extra_vars:
              key: "{{ event.payload.event_tags.key[0] }}"
              run: "{{ event.payload.host_host }}"