---
- name: Zabbix test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
  rules:
    - name: debug
      condition: event.payload.event_name is match("Network Options", ignorecase=true)
      action:
        debug:
