---
- name: Increase Filesystem Size
  hosts: "{{ run }}"
  become: yes

  tasks:
    - name: Get lspath output
      shell: "lspath"
      register: lspath_output

    - name: Analyze path redundancy
      shell: |
        echo "{{ lspath_output.stdout }}" | awk '{print $2, $3}' | sort | uniq -c | awk '$1 < 2 {print $2, $3, "not redundant"}'
      register: redundancy_check
      failed_when: redundancy_check.stdout != ""

    - name: Display redundancy check results
      debug:
        msg: "Redundancy check for each device: {{ redundancy_check.stdout }}"