---
- name: NOC Review
  hosts: "{{ run }}"
  become: yes
  vars:
    context: none

  tasks:
    - name: Get list of currently logged in users
      command: who
      register: logged_in_users

    - name: Print list of currently logged in users
      debug:
        msg: "{{ logged_in_users.stdout_lines }}"

    - name: Run lspath
      command: lspath
      register: lspath_output
      when: context == "fiber"

    - name: Print lspath
      debug:
        msg: "{{ lspath_output.stdout_lines }}"

    - name: Send message to Teams
      uri:
        url: "{{ teams_url }}"
        method: POST
        body_format: json
        body: 
          title: "APPROVAL NEEDED (Fiber Adapter Tuning)"
          text: "{{ run }}: Fiber Adapter Tunables. Login to review the impact and approve this automation."
      when: context == "fiber"